// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Ctor_WhenCalledWithValues_MinValueBecomesFirst731()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[1];
    this.Ctor_WhenCalledWithValues_MinValueBecomesFirst(keyValuePairs);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Ctor_WhenCalledWithValues_MinValueBecomesFirst885()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[5];
    this.Ctor_WhenCalledWithValues_MinValueBecomesFirst(keyValuePairs);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Ctor_WhenCalledWithValues_MinValueBecomesFirst776()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[7];
    this.Ctor_WhenCalledWithValues_MinValueBecomesFirst(keyValuePairs);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Ctor_WhenCalledWithValues_MinValueBecomesFirst973()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[8];
    this.Ctor_WhenCalledWithValues_MinValueBecomesFirst(keyValuePairs);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Ctor_WhenCalledWithValues_MinValueBecomesFirst714()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[11];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(1, 1);
    keyValuePairs[1] = s0;
    KeyValuePair<int, int> s1 = new KeyValuePair<int, int>(1, 1);
    keyValuePairs[2] = s1;
    KeyValuePair<int, int> s2 = new KeyValuePair<int, int>(1, 1);
    keyValuePairs[3] = s2;
    KeyValuePair<int, int> s3 = new KeyValuePair<int, int>(1, 1);
    keyValuePairs[4] = s3;
    KeyValuePair<int, int> s4 = new KeyValuePair<int, int>(1, 1);
    keyValuePairs[5] = s4;
    KeyValuePair<int, int> s5 = new KeyValuePair<int, int>(1, 1);
    keyValuePairs[6] = s5;
    KeyValuePair<int, int> s6 = new KeyValuePair<int, int>(1, 1);
    keyValuePairs[7] = s6;
    this.Ctor_WhenCalledWithValues_MinValueBecomesFirst(keyValuePairs);
}
    }
}
