// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin665()
{
    int[] ints = new int[1];
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin575()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin526()
{
    int[] ints = new int[2];
    ints[0] = 1023;
    ints[1] = 1023;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin11()
{
    int[] ints = new int[2];
    ints[0] = 1;
    ints[1] = 512;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin102()
{
    int[] ints = new int[3];
    ints[0] = 1;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin893()
{
    int[] ints = new int[4];
    ints[0] = 56;
    ints[1] = 1;
    ints[2] = 512;
    ints[3] = 56;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin583()
{
    int[] ints = new int[5];
    ints[0] = 1;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void GetValue_WhenAddedSeveralElements_ReturnsMin628()
{
    int[] ints = new int[17];
    ints[0] = 1023;
    ints[1] = 1022;
    ints[2] = 1022;
    ints[3] = 1022;
    ints[4] = 921;
    ints[5] = 894;
    ints[6] = 831;
    ints[7] = 830;
    ints[8] = -2147482824;
    ints[9] = 817;
    ints[10] = 896;
    ints[11] = 817;
    ints[12] = 825;
    ints[13] = 829;
    ints[14] = 825;
    ints[15] = 768;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void GetValue_WhenAddedSeveralElements_ReturnsMin433()
{
    int[] ints = new int[17];
    ints[0] = 1023;
    ints[1] = 1022;
    ints[2] = 1022;
    ints[3] = 1022;
    ints[4] = 1021;
    ints[5] = 1016;
    ints[6] = 1016;
    ints[7] = 1016;
    ints[8] = -1073741054;
    ints[9] = 779;
    ints[10] = 66176;
    ints[11] = -1073740991;
    ints[12] = -1073741017;
    ints[13] = -1073740991;
    ints[14] = -1073741053;
    ints[15] = -1073740992;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void GetValue_WhenAddedSeveralElements_ReturnsMin917()
{
    int[] ints = new int[17];
    ints[0] = 511;
    ints[1] = 510;
    ints[2] = 510;
    ints[3] = 510;
    ints[4] = 504;
    ints[5] = 504;
    ints[6] = 508;
    ints[7] = 504;
    ints[8] = -2147483328;
    ints[9] = -2147483247;
    ints[10] = -2147417984;
    ints[11] = -2147483255;
    ints[12] = -2147483087;
    ints[13] = -2147483327;
    ints[14] = -2147483135;
    ints[15] = -2147483264;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
    }
}
