// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_WhenNewMinValueIsAdded_ItBecomesFirstValue240()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[0];
    this.Add_WhenNewMinValueIsAdded_ItBecomesFirstValue<int>
        (keyValuePairs, default(KeyValuePair<int, int>));
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_WhenNewMinValueIsAdded_ItBecomesFirstValue100()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[1];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(1, default(int));
    keyValuePairs[0] = s0;
    this.Add_WhenNewMinValueIsAdded_ItBecomesFirstValue<int>
        (keyValuePairs, default(KeyValuePair<int, int>));
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_WhenNewMinValueIsAdded_ItBecomesFirstValue648()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[2];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(1, default(int));
    keyValuePairs[0] = s0;
    KeyValuePair<int, int> s1 = new KeyValuePair<int, int>(2, default(int));
    keyValuePairs[1] = s1;
    this.Add_WhenNewMinValueIsAdded_ItBecomesFirstValue<int>
        (keyValuePairs, default(KeyValuePair<int, int>));
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_WhenNewMinValueIsAdded_ItBecomesFirstValue907()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[2];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(1, default(int));
    keyValuePairs[0] = s0;
    KeyValuePair<int, int> s1 = new KeyValuePair<int, int>(1, default(int));
    keyValuePairs[1] = s1;
    this.Add_WhenNewMinValueIsAdded_ItBecomesFirstValue<int>
        (keyValuePairs, default(KeyValuePair<int, int>));
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_WhenNewMinValueIsAdded_ItBecomesFirstValue552()
{
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[4];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(504, default(int));
    keyValuePairs[0] = s0;
    KeyValuePair<int, int> s1 = new KeyValuePair<int, int>(505, default(int));
    keyValuePairs[1] = s1;
    KeyValuePair<int, int> s2 = new KeyValuePair<int, int>(377, default(int));
    keyValuePairs[2] = s2;
    KeyValuePair<int, int> s3 = new KeyValuePair<int, int>(316, default(int));
    keyValuePairs[3] = s3;
    this.Add_WhenNewMinValueIsAdded_ItBecomesFirstValue<int>
        (keyValuePairs, default(KeyValuePair<int, int>));
}
    }
}
