// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenAddedSeveralElements_ReturnsMin665()
{
    int[] ints = new int[1];
    this.GetFirst_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenAddedSeveralElements_ReturnsMin575()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.GetFirst_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenAddedSeveralElements_ReturnsMin526()
{
    int[] ints = new int[2];
    ints[0] = 1023;
    ints[1] = 1023;
    this.GetFirst_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenAddedSeveralElements_ReturnsMin102()
{
    int[] ints = new int[3];
    ints[0] = 1;
    this.GetFirst_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenAddedSeveralElements_ReturnsMin316()
{
    int[] ints = new int[5];
    ints[0] = 1023;
    ints[1] = 1022;
    ints[2] = 1022;
    this.GetFirst_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void GetFirst_WhenAddedSeveralElements_ReturnsMin850()
{
    int[] ints = new int[16];
    ints[0] = 1023;
    ints[1] = 1023;
    ints[2] = 1023;
    ints[3] = 1022;
    ints[4] = 1021;
    ints[5] = 1021;
    ints[8] = 48;
    ints[9] = 48;
    ints[10] = 128;
    ints[12] = 288;
    this.GetFirst_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void GetFirst_WhenAddedSeveralElements_ReturnsMin493()
{
    int[] ints = new int[16];
    ints[0] = 1023;
    ints[1] = 1023;
    ints[2] = 1023;
    ints[3] = 6;
    ints[4] = 5;
    ints[5] = 5;
    ints[6] = -2147483644;
    ints[7] = -2147483644;
    ints[8] = -2147483520;
    ints[9] = -2147483644;
    ints[10] = -2147483644;
    ints[11] = -2147483520;
    ints[12] = -2147483644;
    ints[13] = -2147483644;
    ints[14] = -2147483644;
    ints[15] = int.MinValue;
    this.GetFirst_WhenAddedSeveralElements_ReturnsMin(ints);
}
    }
}
