// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented28()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[1];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented709()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[2];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented456()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[2];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(1, 0);
    tuples[1] = s1;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented726()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[3];
    Tuple<int, int> s0 = new Tuple<int, int>(257, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(2, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(1, 0);
    tuples[2] = s2;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented649()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[3];
    Tuple<int, int> s0 = new Tuple<int, int>(802, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(802, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(802, 0);
    tuples[2] = s2;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented83()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[4];
    Tuple<int, int> s0 = new Tuple<int, int>(17, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(17, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(0, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(0, 0);
    tuples[3] = s3;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented27()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[4];
    Tuple<int, int> s0 = new Tuple<int, int>(4, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(0, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(1, 0);
    tuples[3] = s3;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented282()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[5];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(0, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(0, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(0, 0);
    tuples[4] = s4;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented387()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[6];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(0, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(0, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(0, 0);
    tuples[4] = s4;
    Tuple<int, int> s5 = new Tuple<int, int>(0, 0);
    tuples[5] = s5;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented767()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[7];
    Tuple<int, int> s0 = new Tuple<int, int>(580, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(580, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(580, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(148, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(148, 0);
    tuples[4] = s4;
    Tuple<int, int> s5 = new Tuple<int, int>(148, 0);
    tuples[5] = s5;
    Tuple<int, int> s6 = new Tuple<int, int>(137, 0);
    tuples[6] = s6;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented74()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[7];
    Tuple<int, int> s0 = new Tuple<int, int>(641, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(136, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(128, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(121, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(121, 0);
    tuples[4] = s4;
    Tuple<int, int> s5 = new Tuple<int, int>(121, 0);
    tuples[5] = s5;
    Tuple<int, int> s6 = new Tuple<int, int>(92, 0);
    tuples[6] = s6;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented719()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[8];
    Tuple<int, int> s0 = new Tuple<int, int>(516, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(200, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(145, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(144, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(12, 0);
    tuples[4] = s4;
    Tuple<int, int> s5 = new Tuple<int, int>(9, 0);
    tuples[5] = s5;
    Tuple<int, int> s6 = new Tuple<int, int>(1, 0);
    tuples[6] = s6;
    Tuple<int, int> s7 = new Tuple<int, int>(73, 0);
    tuples[7] = s7;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Extract_WhenCalled_CountIsDecremented198()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[3];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(1, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(1, 0);
    tuples[2] = s2;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void Extract_WhenCalled_CountIsDecremented956()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[21];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(0, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(0, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(0, 0);
    tuples[4] = s4;
    Tuple<int, int> s5 = new Tuple<int, int>(0, 0);
    tuples[5] = s5;
    Tuple<int, int> s6 = new Tuple<int, int>(0, 0);
    tuples[6] = s6;
    Tuple<int, int> s7 = new Tuple<int, int>(0, 0);
    tuples[7] = s7;
    Tuple<int, int> s8 = new Tuple<int, int>(0, 0);
    tuples[8] = s8;
    Tuple<int, int> s9 = new Tuple<int, int>(0, 0);
    tuples[9] = s9;
    Tuple<int, int> s10 = new Tuple<int, int>(0, 0);
    tuples[10] = s10;
    Tuple<int, int> s11 = new Tuple<int, int>(0, 0);
    tuples[11] = s11;
    Tuple<int, int> s12 = new Tuple<int, int>(0, 0);
    tuples[12] = s12;
    Tuple<int, int> s13 = new Tuple<int, int>(0, 0);
    tuples[13] = s13;
    Tuple<int, int> s14 = new Tuple<int, int>(0, 0);
    tuples[14] = s14;
    Tuple<int, int> s15 = new Tuple<int, int>(0, 0);
    tuples[15] = s15;
    Tuple<int, int> s16 = new Tuple<int, int>(0, 0);
    tuples[16] = s16;
    Tuple<int, int> s17 = new Tuple<int, int>(0, 0);
    tuples[17] = s17;
    Tuple<int, int> s18 = new Tuple<int, int>(0, 0);
    tuples[18] = s18;
    Tuple<int, int> s19 = new Tuple<int, int>(0, 0);
    tuples[19] = s19;
    Tuple<int, int> s20 = new Tuple<int, int>(0, 0);
    tuples[20] = s20;
    this.Extract_WhenCalled_CountIsDecremented<int, int>(tuples);
}
    }
}
