// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue554()
{
    int[] ints = new int[1];
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue370()
{
    int[] ints = new int[2];
    ints[0] = 1023;
    ints[1] = 1023;
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue636()
{
    int[] ints = new int[3];
    ints[0] = 1023;
    ints[1] = 1023;
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue914()
{
    int[] ints = new int[4];
    ints[0] = 1023;
    ints[1] = 1023;
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue780()
{
    int[] ints = new int[5];
    ints[0] = 1023;
    ints[1] = 1023;
    ints[2] = 2;
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue761()
{
    int[] ints = new int[6];
    ints[0] = 1023;
    ints[1] = 1023;
    ints[2] = 2;
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue255()
{
    int[] ints = new int[8];
    ints[0] = 1023;
    ints[1] = 1023;
    ints[2] = 2;
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue108()
{
    int[] ints = new int[9];
    ints[0] = 1023;
    ints[1] = 1023;
    ints[2] = 2;
    this.ExtractFirst_WhenHeapContainsSeveralElements_ResultIsMinValue(ints);
}
    }
}
