// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapUsageExamples
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks16()
{
    int[] ints = new int[0];
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks554()
{
    int[] ints = new int[1];
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks685()
{
    int[] ints = new int[2];
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks612()
{
    int[] ints = new int[3];
    ints[0] = 17;
    ints[1] = 17;
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks544()
{
    int[] ints = new int[4];
    ints[0] = 17;
    ints[1] = 17;
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks73()
{
    int[] ints = new int[4];
    ints[0] = 353;
    ints[1] = 352;
    ints[2] = 352;
    ints[3] = 1;
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks247()
{
    int[] ints = new int[5];
    ints[0] = 17;
    ints[1] = 17;
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
public void HeapSortWorks850()
{
    int[] ints = new int[7];
    ints[0] = 17;
    ints[1] = 17;
    this.HeapSortWorks(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapUsageExamples))]
[Ignore("the test state was: path bounds exceeded")]
public void HeapSortWorks225()
{
    int[] ints = new int[11];
    ints[0] = 513;
    ints[1] = 4;
    ints[2] = 5;
    this.HeapSortWorks(ints);
}
    }
}
