// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_HeapIsNotEmpty_ReturnsMinValue665()
{
    int[] ints = new int[1];
    this.GetFirst_HeapIsNotEmpty_ReturnsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_HeapIsNotEmpty_ReturnsMinValue575()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.GetFirst_HeapIsNotEmpty_ReturnsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_HeapIsNotEmpty_ReturnsMinValue526()
{
    int[] ints = new int[2];
    ints[0] = 1023;
    ints[1] = 1023;
    this.GetFirst_HeapIsNotEmpty_ReturnsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_HeapIsNotEmpty_ReturnsMinValue102()
{
    int[] ints = new int[3];
    ints[0] = 1;
    this.GetFirst_HeapIsNotEmpty_ReturnsMinValue(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_HeapIsNotEmpty_ReturnsMinValue316()
{
    int[] ints = new int[5];
    ints[0] = 1023;
    ints[1] = 1022;
    ints[2] = 1022;
    this.GetFirst_HeapIsNotEmpty_ReturnsMinValue(ints);
}
    }
}
