// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using System.Collections.Generic;
using PexBinaryHeap;
using PexBinaryHeap.Tests.Pex.Factories;
using Microsoft.Pex.Framework;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenCalled_CountStaysTheSame952()
{
    BinaryHeap<int, int> binaryHeap;
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[1];
    binaryHeap = BinaryHeapFactory.Create(keyValuePairs);
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(binaryHeap);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenCalled_CountStaysTheSame581()
{
    BinaryHeap<int, int> binaryHeap;
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[2];
    binaryHeap = BinaryHeapFactory.Create(keyValuePairs);
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(binaryHeap);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void GetFirst_WhenCalled_CountStaysTheSame03()
{
    BinaryHeap<int, int> binaryHeap;
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[41];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(4, default(int));
    keyValuePairs[0] = s0;
    KeyValuePair<int, int> s1 = new KeyValuePair<int, int>(4, default(int));
    keyValuePairs[1] = s1;
    KeyValuePair<int, int> s2 = new KeyValuePair<int, int>(12, default(int));
    keyValuePairs[2] = s2;
    binaryHeap = BinaryHeapFactory.Create(keyValuePairs);
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenCalled_CountStaysTheSame690()
{
    BinaryHeap<int, int> binaryHeap;
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[3];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(552, default(int));
    keyValuePairs[0] = s0;
    KeyValuePair<int, int> s1 = new KeyValuePair<int, int>(74, default(int));
    keyValuePairs[1] = s1;
    KeyValuePair<int, int> s2 = new KeyValuePair<int, int>(74, default(int));
    keyValuePairs[2] = s2;
    binaryHeap = BinaryHeapFactory.Create(keyValuePairs);
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(binaryHeap);
    PexAssert.IsNotNull((object)binaryHeap);
}
    }
}
