// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin665()
{
    int[] ints = new int[1];
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin575()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin526()
{
    int[] ints = new int[2];
    ints[0] = 1023;
    ints[1] = 1023;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin11()
{
    int[] ints = new int[2];
    ints[0] = 1;
    ints[1] = 512;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin361()
{
    int[] ints = new int[3];
    ints[1] = 512;
    ints[2] = 1;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[PexRaisedContractException]
public void GetValue_WhenAddedSeveralElements_ReturnsMinThrowsContractException734()
{
    int[] ints = new int[5];
    ints[0] = 1023;
    ints[1] = 1022;
    ints[2] = 1022;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin102()
{
    int[] ints = new int[3];
    ints[0] = 1;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetValue_WhenAddedSeveralElements_ReturnsMin856()
{
    int[] ints = new int[11];
    ints[0] = -2147483647;
    ints[1] = -2147483392;
    ints[2] = 512;
    ints[3] = -2147483136;
    ints[4] = -2147483647;
    ints[5] = -2147483647;
    ints[6] = -2147483647;
    ints[7] = 1;
    ints[9] = 1;
    this.GetValue_WhenAddedSeveralElements_ReturnsMin(ints);
}
    }
}
