// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using PexBinaryHeap;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.ExtendedReflection.DataAccess;
using System.Collections.Generic;
using PexBinaryHeap.Tests.Pex.Factories;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues160()
{
    BinaryHeap<int, int> binaryHeap;
    binaryHeap = BinaryHeapFactory.Create();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[0];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues884()
{
    BinaryHeap<int, int> binaryHeap;
    binaryHeap = BinaryHeapFactory.Create();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[1];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues440()
{
    BinaryHeap<int, int> binaryHeap;
    binaryHeap = BinaryHeapFactory.Create();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[1];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(1, default(int));
    keyValuePairs[0] = s0;
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues16001()
{
    BinaryHeap<int, int> binaryHeap;
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[0];
    binaryHeap = BinaryHeapFactory.Create(keyValuePairs);
    KeyValuePair<int, int>[] keyValuePairs1 = new KeyValuePair<int, int>[0];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs1);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues316()
{
    BinaryHeap<int, int> binaryHeap;
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[1];
    binaryHeap = BinaryHeapFactory.Create(keyValuePairs);
    KeyValuePair<int, int>[] keyValuePairs1 = new KeyValuePair<int, int>[0];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs1);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues952()
{
    BinaryHeap<int, int> binaryHeap;
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[1];
    KeyValuePair<int, int> s0 = new KeyValuePair<int, int>(1, default(int));
    keyValuePairs[0] = s0;
    binaryHeap = BinaryHeapFactory.Create(keyValuePairs);
    KeyValuePair<int, int>[] keyValuePairs1 = new KeyValuePair<int, int>[1];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs1);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues27()
{
    BinaryHeap<int, int> binaryHeap;
    binaryHeap = BinaryHeapFactory.Create();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[2];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues250()
{
    BinaryHeap<int, int> binaryHeap;
    binaryHeap = BinaryHeapFactory.Create();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[3];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues842()
{
    BinaryHeap<int, int> binaryHeap;
    binaryHeap = BinaryHeapFactory.Create();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[4];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs);
    PexAssert.IsNotNull((object)binaryHeap);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void Add_SeveralValues_CountIsIncrementedByCountOfNewValues969()
{
    BinaryHeap<int, int> binaryHeap;
    binaryHeap = BinaryHeapFactory.Create();
    KeyValuePair<int, int>[] keyValuePairs = new KeyValuePair<int, int>[5];
    this.Add_SeveralValues_CountIsIncrementedByCountOfNewValues<int, int>
        (binaryHeap, keyValuePairs);
    PexAssert.IsNotNull((object)binaryHeap);
}
    }
}
