// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace PexBinaryHeap.Tests.Pex
{
    public partial class BinaryHeapTests
    {
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenCalled_CountStaysTheSame28()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[1];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenCalled_CountStaysTheSame709()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[2];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenCalled_CountStaysTheSame726()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[3];
    Tuple<int, int> s0 = new Tuple<int, int>(257, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(2, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(1, 0);
    tuples[2] = s2;
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
public void GetFirst_WhenCalled_CountStaysTheSame282()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[5];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(0, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(0, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(0, 0);
    tuples[4] = s4;
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(tuples);
}
[Test]
[PexGeneratedBy(typeof(BinaryHeapTests))]
[Ignore("the test state was: path bounds exceeded")]
public void GetFirst_WhenCalled_CountStaysTheSame817()
{
    Tuple<int, int>[] tuples = new Tuple<int, int>[17];
    Tuple<int, int> s0 = new Tuple<int, int>(0, 0);
    tuples[0] = s0;
    Tuple<int, int> s1 = new Tuple<int, int>(0, 0);
    tuples[1] = s1;
    Tuple<int, int> s2 = new Tuple<int, int>(0, 0);
    tuples[2] = s2;
    Tuple<int, int> s3 = new Tuple<int, int>(0, 0);
    tuples[3] = s3;
    Tuple<int, int> s4 = new Tuple<int, int>(0, 0);
    tuples[4] = s4;
    Tuple<int, int> s5 = new Tuple<int, int>(0, 0);
    tuples[5] = s5;
    Tuple<int, int> s6 = new Tuple<int, int>(0, 0);
    tuples[6] = s6;
    Tuple<int, int> s7 = new Tuple<int, int>(0, 0);
    tuples[7] = s7;
    Tuple<int, int> s8 = new Tuple<int, int>(0, 0);
    tuples[8] = s8;
    Tuple<int, int> s9 = new Tuple<int, int>(0, 0);
    tuples[9] = s9;
    Tuple<int, int> s10 = new Tuple<int, int>(0, 0);
    tuples[10] = s10;
    Tuple<int, int> s11 = new Tuple<int, int>(0, 0);
    tuples[11] = s11;
    Tuple<int, int> s12 = new Tuple<int, int>(0, 0);
    tuples[12] = s12;
    Tuple<int, int> s13 = new Tuple<int, int>(0, 0);
    tuples[13] = s13;
    Tuple<int, int> s14 = new Tuple<int, int>(0, 0);
    tuples[14] = s14;
    Tuple<int, int> s15 = new Tuple<int, int>(0, 0);
    tuples[15] = s15;
    Tuple<int, int> s16 = new Tuple<int, int>(0, 0);
    tuples[16] = s16;
    this.GetFirst_WhenCalled_CountStaysTheSame<int, int>(tuples);
}
    }
}
